name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Feature check
        run: cargo check --features napi,wasm
